export const portfolioData = {
  person: {
    name: "Kiran Gautham",
    role: "Full Stack Developer | AI/ML Engineer | Cybersecurity Builder",
    location: "Palakkad, Kerala, India",
    email: "kirangautham82899@gmail.com",
    phone: "+91 8289961249",
    github: "https://github.com/kirangautham-82899",
    githubHandle: "kirangautham-82899",
    linkedin: "https://www.linkedin.com/in/kiran-gautham-b16319358/",
    resume: "/Kiran-Gautham-Resume.pdf",
    summary:
      "Computer Science graduate building production-grade web platforms, real-time systems, AI-integrated tools, and cybersecurity-focused applications across React, Node.js, Python, FastAPI, databases, and interactive visualization.",
  },
  heroStats: [
    { value: "8.18", label: "CSE CGPA" },
    { value: "15+", label: "Recognized teams & awards" },
    { value: "5", label: "Signature engineering builds" },
    { value: "2026", label: "B.Tech graduation" },
  ],
  focusAreas: [
    { icon: "Code2", title: "Full Stack Product Engineering", text: "Next.js, React, Node.js, Express, REST APIs, auth flows, dashboards, and production iteration." },
    { icon: "BrainCircuit", title: "AI/ML & Explainability", text: "CNN-LSTM trajectory prediction, PyTorch, Grad-CAM, OpenCV, MediaPipe, and interpretable systems." },
    { icon: "ShieldCheck", title: "Cybersecurity Systems", text: "Phishing defense, ransomware heuristics, honeypots, file integrity monitoring, and secure role-based access." },
    { icon: "Zap", title: "Real-Time Experiences", text: "WebSockets, Socket.IO, live alerts, concurrent workflows, low-latency media controls, and Unity 3D visualization." },
  ],
  skills: [
    { name: "React / Next.js", level: 94, group: "Frontend" },
    { name: "TypeScript", level: 90, group: "Languages" },
    { name: "Node.js / Express", level: 90, group: "Backend" },
    { name: "Python / FastAPI", level: 88, group: "Backend" },
    { name: "AI/ML / PyTorch", level: 84, group: "AI" },
    { name: "Cybersecurity", level: 86, group: "Security" },
    { name: "MongoDB / PostgreSQL", level: 84, group: "Data" },
    { name: "WebSockets / Socket.IO", level: 88, group: "Realtime" },
    { name: "OpenCV / MediaPipe", level: 82, group: "Vision" },
    { name: "Docker / Git", level: 80, group: "DevOps" },
  ],
  techStack: [
    "React",
    "Next.js",
    "TypeScript",
    "Tailwind CSS",
    "Framer Motion",
    "Node.js",
    "Express.js",
    "FastAPI",
    "Python",
    "JavaScript",
    "Java",
    "C",
    "PHP",
    "REST APIs",
    "JWT",
    "WebSockets",
    "Socket.IO",
    "MongoDB",
    "PostgreSQL",
    "MySQL",
    "Firebase",
    "Supabase",
    "PyTorch",
    "CNN-LSTM",
    "Grad-CAM",
    "Unity",
    "OpenCV",
    "MediaPipe",
    "Docker",
    "Git",
    "Linux",
    "Sequelize ORM",
  ],
  experience: [
    {
      role: "Software Engineer Intern",
      company: "Sustains Energy",
      location: "Bangalore",
      period: "Oct 2025 - Present",
      icon: "BriefcaseBusiness",
      bullets: [
        "Developed and maintained full-stack features for production-grade energy analytics software using React.js and Node.js/Express.js.",
        "Integrated REST APIs, optimized backend services, and collaborated across testing, debugging, agile releases, product management, and digital marketing integration.",
      ],
    },
  ],
  projects: [
    {
      title: "Explainable Vehicle Trajectory Prediction",
      subtitle: "Autonomous systems research platform",
      period: "Jan - May 2026",
      image: "/projects/trajectory.png",
      live: "#contact",
      github: "https://github.com/kirangautham-82899/Explainable-Vehicle-Trajectory-Prediction",
      tech: ["Python", "PyTorch", "CNN-LSTM", "Grad-CAM", "Unity 3D"],
      accent: "from-cyan-300 to-indigo-400",
      impact:
        "Hybrid CNN-LSTM model for multi-vehicle prediction on the NGSIM dataset with Grad-CAM explainability and Unity 3D real-time trajectory visualization.",
    },
    {
      title: "ZYNTRIX",
      subtitle: "Phishing & social engineering defense",
      period: "Jan - Feb 2026",
      image: "/projects/zyntrix.png",
      live: "#contact",
      github: "https://github.com/kirangautham-82899/Zyntrix-A-Real-Time-Explainable-Phishing-Social-Engineering-Defense-Platform",
      tech: ["Next.js", "React", "Python", "FastAPI", "JWT", "WebSockets"],
      accent: "from-emerald-300 to-cyan-400",
      impact:
        "AI-powered phishing detection platform with real-time FastAPI threat analysis, live WebSocket alerts, and JWT-secured role-based multi-user access.",
    },
    {
      title: "Real-Time Incident Reporting Platform",
      subtitle: "Live operations dashboard",
      period: "Jan - Mar 2026",
      image: "/projects/incident.png",
      live: "#contact",
      github: "https://github.com/kirangautham-82899/Incident-Tracker",
      tech: ["React", "Node.js", "Express.js", "Socket.IO", "MongoDB"],
      accent: "from-violet-300 to-fuchsia-400",
      impact:
        "Concurrent incident workflow with WebSocket notifications, analytics dashboard, and MongoDB-backed REST API for multi-user reporting.",
    },
    {
      title: "Hand Gesture Media Controller",
      subtitle: "Computer vision desktop app",
      period: "Jul 2025",
      image: "/projects/gesture.png",
      live: "#contact",
      github: "https://github.com/kirangautham-82899/Hand-Gesture-Controlled-Media-Controller",
      tech: ["Python", "OpenCV", "MediaPipe", "PyQt6", "Pycaw"],
      accent: "from-amber-200 to-rose-300",
      impact:
        "Low-latency desktop controller mapping webcam hand gestures to media controls with downscaled-frame detection, cooldown logic, and dual-mode UI.",
    },
    {
      title: "SecureVault",
      subtitle: "Ransomware detection & prevention",
      period: "Jul 2025",
      image: "/projects/securevault.png",
      live: "#contact",
      github: "https://github.com/kirangautham-82899/SecureVault-Ransomware-Detection-Prevention-System",
      tech: ["Python", "PyQt6", "watchdog", "psutil", "OpenCV"],
      accent: "from-sky-300 to-emerald-300",
      impact:
        "Cybersecurity tool combining SHA-256 integrity monitoring, honeypot deception, and CPU heuristic analysis for ransomware-like activity alerts.",
    },
  ],
  publication: {
    title: "Explainable Deep Learning Approaches for Vehicle Trajectory Prediction in Autonomous Systems",
    venue: "International Journal of Research and Analytical Reviews (IJRASET), 2025",
    doi: "https://doi.org/10.22214/ijraset.2025.76078",
    icon: "GraduationCap",
  },
  achievements: [
    { icon: "Trophy", title: "Top 15 Teams", text: "Kyberastra 2025" },
    { icon: "Medal", title: "Second Prize", text: "IIT Jodhpur Web Dev Hackathon" },
    { icon: "Sparkles", title: "Special Innovation Award", text: "IIT Palakkad" },
    { icon: "Award", title: "B.Tech Class Topper Award", text: "Academic excellence in Computer Science Engineering" },
    { icon: "Binary", title: "Second Prize", text: "CODEATHON, Ahalia SEaT" },
    { icon: "BadgeCheck", title: "Best Project Award", text: "Department of Computer Science" },
    { icon: "Radar", title: "Adobe India Hackathon", text: "Competitive hackathon recognition" },
  ],
  certifications: [
    "React - HackerRank",
    "Java - HackerRank",
    "Web Development - NSDC, Internshala",
    "Python - NSDC, Internshala",
    "Software Testing - NPTEL",
  ],
  leadership: [
    {
      title: "UG Class Representative (CSE)",
      org: "Ahalia School of Engineering and Technology",
      text: "Represented the Computer Science cohort while coordinating academic communication and student initiatives.",
      icon: "Users",
    },
    {
      title: "College Magazine Editor",
      org: "Ahalia School of Engineering and Technology",
      text: "Helped shape editorial direction and student storytelling across college publication work.",
      icon: "Layers3",
    },
    {
      title: "Organizer & Volunteer - Smart India Hackathon Prelims",
      org: "Ahalia School of Engineering and Technology",
      text: "Coordinated registration, scheduling, and on-ground operations for seamless hackathon execution.",
      icon: "Network",
    },
    {
      title: "Volunteer - TECHFEST & KETCON 2024",
      org: "APJ Abdul Kalam Technological University",
      text: "Managed logistics, resource allocation, and deadline adherence across concurrent technical fest events.",
      icon: "Terminal",
    },
  ],
  education: {
    degree: "B.Tech - Computer Science Engineering",
    school: "Ahalia School of Engineering and Technology, Palakkad",
    period: "May 2026",
    score: "CGPA 8.18 / 10",
  },
  contactLinks: [
    { label: "Email", href: "mailto:kirangautham82899@gmail.com", icon: "Mail" },
    { label: "GitHub", href: "https://github.com/kirangautham-82899", icon: "Github" },
    { label: "LinkedIn", href: "https://www.linkedin.com/in/kiran-gautham-b16319358/", icon: "Linkedin" },
    { label: "Phone", href: "tel:+918289961249", icon: "Phone" },
    { label: "Palakkad", href: "#contact", icon: "MapPin" },
  ],
};

export type PortfolioData = typeof portfolioData;
